/**
 * Trusted harness — runs INSIDE the E2B sandbox.
 *
 * Responsibilities:
 *   1. Parse the WorkflowEvent from the WORKFLOW_EVENT_JSON env var.
 *   2. Build a stub `tools` object (console.log for actions, mock data for queries).
 *   3. Dynamically import the LLM-generated `workflow.mjs` and call its default export.
 *
 * This file is written verbatim into the sandbox filesystem before each run.
 * It is NOT generated by the LLM — it is part of our trusted codebase.
 */

const eventJson = process.env.WORKFLOW_EVENT_JSON;
if (!eventJson) {
  console.error("WORKFLOW_EVENT_JSON env var is missing");
  process.exit(1);
}

let event;
try {
  event = JSON.parse(eventJson);
} catch (err) {
  console.error("Failed to parse WORKFLOW_EVENT_JSON:", err.message);
  process.exit(1);
}

const tools = {
  async getSessions(options) {
    console.log(
      JSON.stringify({ tool: "getSessions", options: options ?? {} }),
    );
    return [
      {
        id: "00000000-0000-0000-0000-000000000001",
        customerName: "Alice Mock",
        status: "closed",
        sentiment: "angry",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "00000000-0000-0000-0000-000000000002",
        customerName: "Bob Mock",
        status: "open",
        sentiment: null,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ];
  },

  async getMessages(options) {
    console.log(
      JSON.stringify({ tool: "getMessages", options: options ?? {} }),
    );
    return [
      {
        id: "00000000-0000-0000-0000-000000000010",
        sessionId: "00000000-0000-0000-0000-000000000001",
        authorRole: "customer",
        body: "I am very unhappy with the service!",
        createdAt: new Date().toISOString(),
      },
      {
        id: "00000000-0000-0000-0000-000000000011",
        sessionId: "00000000-0000-0000-0000-000000000001",
        authorRole: "agent",
        body: "I am sorry to hear that. Let me help.",
        createdAt: new Date().toISOString(),
      },
    ];
  },

  async sendEmail(to, subject, body) {
    const apiKey = process.env.RESEND_API_KEY;
    const from = process.env.RESEND_FROM_EMAIL || "onboarding@resend.dev";

    if (!apiKey) {
      console.log(
        JSON.stringify({ tool: "sendEmail", to, subject, body, mock: true }),
      );
      return;
    }

    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ from, to: [to], subject, text: body }),
    });

    const result = await res.json();

    if (!res.ok) {
      throw new Error(
        `sendEmail failed (${res.status}): ${JSON.stringify(result)}`,
      );
    }

    console.log(
      JSON.stringify({ tool: "sendEmail", to, subject, resendId: result.id }),
    );
  },

  async sendSlackChannelMessage(channelName, message) {
    console.log(
      JSON.stringify({ tool: "sendSlackChannelMessage", channelName, message }),
    );
  },
};

try {
  const mod = await import("./workflow.mjs");
  const run = mod.default;
  if (typeof run !== "function") {
    throw new Error("workflow.mjs must export a default async function");
  }
  await run(event, tools);
} catch (err) {
  console.error("Workflow execution failed:", err);
  process.exit(1);
}
