-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table 1: The Dummy App Data (Sessions)
CREATE TABLE sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    customer_name VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'open', -- 'open' or 'closed'
    sentiment VARCHAR(50), -- 'happy', 'neutral', 'angry' (populated on close)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table 2: The Agentic Builder (Workflows)
CREATE TABLE workflows (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    trigger_event VARCHAR(100) NOT NULL, -- e.g., 'session.closed'
    original_prompt TEXT NOT NULL, -- The user's prompt (e.g., "Send slack message...")
    generated_code TEXT NOT NULL, -- The sandboxed JS code generated by the LLM
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Index for quick lookups when an event fires
CREATE INDEX idx_workflows_trigger_event ON workflows(trigger_event) WHERE is_active = true;
